### ISSUE TITLE
DMMGamePlayerFastLauncher doesn't create shortcuts for any game, but does for DMMGamePlayer.

### ISSUE THREAD

**Issue by Dario011** [fa0311/DMMGamePlayerFastLauncher#117] opened 2024-02-01 00:00 UTC
### OS

Windows 10 (22H2)

### Bug Description

The application does not create any shortcut to Princess Connect Re:Dive, in any of the options (Normal and UAC) to create shortcuts, but it allows me to create a shortcut to DMM Game Player with the custom token.
And if I try to create the shortcut via the "Edit Shortcut" option, it deletes the .json configuration file.

Tested with versions 5.3 (the latest up-to-date version) and 5.2.0.

**Comment by fa0311** [comment] 2024-02-02 04:27
I could not reproduce it in my environment.
Can I enable [Setting] -> [Edit Shortcut] -> [Show Debug Window] to send logs?
(Note that FastLauncher must be restarted after saving the settings)
Also, if the log contains Token, please mask it.

**Comment by Dario011** [comment] 2024-02-02 19:11
I got to activate the mentioned options, and I already have a log (with the tokens and another IDs removed, with the **_[REDACTED]_**).

And it seems that the problem is that I get to create the shortcut, but with the name of the game in Japanese, which causes that it is not done, the syntax of the shortcut is shown in the log.

I managed to recreate the shortcut from the shortcut syntax for the Launcher, and then I got it to work, but I ALWAYS have to hit "Run as administrator".

[log.txt](https://github.com/fa0311/DMMGamePlayerFastLauncher/files/14144267/log.txt)

**Comment by fa0311** [comment] 2024-02-05 04:21
Thanks for providing the logs!
> And it seems that the problem is that I get to create the shortcut, but with the name of the game in Japanese, which causes that it is not done, the syntax of the shortcut is shown in the log.

Is it true that I cannot create shortcuts in Japanese?
I am using Japanese Windows, so I can create them, but they may not be available in other countries.

**Comment by fa0311** [comment] 2024-02-05 07:37
filename is now used as the shortcut name if the following conditions are met
If Japanese(cp932) is the cause of this issue, it will probably be fixed.
- If the OS is not Japanese
- If the game name contains Japanese characters


https://github.com/fa0311/DMMGamePlayerFastLauncher/pull/119/files#diff-712607c6a48a2cbcc42641ff37a30f4a479d3e8c31fde554973fdf69e1f73338R163-R171

**Comment by fa0311** [comment] 2024-02-07 01:41
Maybe that was fixed in v5.4.0.

**Closed by fa0311** 2024-02-07 01:41 UTC
Labels: bug
