### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by wrandifan** [fa0311/DMMGamePlayerFastLauncher#61] opened 2023-03-22 21:46 UTC
![image](https://user-images.githubusercontent.com/17224332/227045838-5f6a1daf-2967-4a1e-89e2-f612a999227a.png)

**Comment by fa0311** [comment] 2023-03-23 16:37
This may be a duplicate of #60.
Is it possible to install and run [v4.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.9.0)

**Closed** 2023-06-11 15:41 UTC
